//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BaseReq.proto
// Note: requires additional types generated from: ReqWrapper.proto
// Note: requires additional types generated from: CampVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaseReq")]
  public partial class BaseReq : global::ProtoBuf.IExtensible
  {
    public BaseReq() {}
    
    private string _authToken = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"authToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string authToken
    {
      get { return _authToken; }
      set { _authToken = value; }
    }
    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private int _sequenceId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sequenceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sequenceId
    {
      get { return _sequenceId; }
      set { _sequenceId = value; }
    }
    private ReqWrapper _reqWrapper = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"reqWrapper", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ReqWrapper reqWrapper
    {
      get { return _reqWrapper; }
      set { _reqWrapper = value; }
    }
    private CampVO _before = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"before", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CampVO before
    {
      get { return _before; }
      set { _before = value; }
    }
    private CampVO _after = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"after", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CampVO after
    {
      get { return _after; }
      set { _after = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}