//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BaseResp.proto
// Note: requires additional types generated from: RespWrapper.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaseResp")]
  public partial class BaseResp : global::ProtoBuf.IExtensible
  {
    public BaseResp() {}
    
    private BaseResp.ErrorType _errorType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BaseResp.ErrorType errorType
    {
      get { return _errorType; }
      set { _errorType = value; }
    }
    private RespWrapper _respWrapper = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"respWrapper", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RespWrapper respWrapper
    {
      get { return _respWrapper; }
      set { _respWrapper = value; }
    }
    private string _errorMessage = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errorMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errorMessage
    {
      get { return _errorMessage; }
      set { _errorMessage = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorType")]
    public enum ErrorType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AuthFailed", Value=1)]
      AuthFailed = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DataVerifyFailed", Value=2)]
      DataVerifyFailed = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IsInFight", Value=3)]
      IsInFight = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IsOffLine", Value=4)]
      IsOffLine = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}