//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BattleOperationVO.proto
// Note: requires additional types generated from: BattleOperationPlaceSoldierVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleOperationVO")]
  public partial class BattleOperationVO : global::ProtoBuf.IExtensible
  {
    public BattleOperationVO() {}
    
    private int _frame;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frame
    {
      get { return _frame; }
      set { _frame = value; }
    }
    private BattleOperationVO.BattleOperationType _battleOperationType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"battleOperationType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BattleOperationVO.BattleOperationType battleOperationType
    {
      get { return _battleOperationType; }
      set { _battleOperationType = value; }
    }
    private BattleOperationPlaceSoldierVO _battleOperationPlaceSoldierVO = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"battleOperationPlaceSoldierVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BattleOperationPlaceSoldierVO battleOperationPlaceSoldierVO
    {
      get { return _battleOperationPlaceSoldierVO; }
      set { _battleOperationPlaceSoldierVO = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"BattleOperationType")]
    public enum BattleOperationType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlaceSoldier", Value=1)]
      PlaceSoldier = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}