//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BattleReplayReq.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleReplayReq")]
  public partial class BattleReplayReq : global::ProtoBuf.IExtensible
  {
    public BattleReplayReq() {}
    
    private long _replayId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"replayId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long replayId
    {
      get { return _replayId; }
      set { _replayId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}