//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BattleReplayVO.proto
// Note: requires additional types generated from: CampVO.proto
// Note: requires additional types generated from: BattleOperationVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleReplayVO")]
  public partial class BattleReplayVO : global::ProtoBuf.IExtensible
  {
    public BattleReplayVO() {}
    
    private CampVO _attacker;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CampVO attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }
    private CampVO _defender;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"defender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CampVO defender
    {
      get { return _defender; }
      set { _defender = value; }
    }
    private readonly global::System.Collections.Generic.List<BattleOperationVO> _battleInputs = new global::System.Collections.Generic.List<BattleOperationVO>();
    [global::ProtoBuf.ProtoMember(3, Name=@"battleInputs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BattleOperationVO> battleInputs
    {
      get { return _battleInputs; }
    }
  
    private long _seed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"seed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long seed
    {
      get { return _seed; }
      set { _seed = value; }
    }
    private int _battleDuration;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"battleDuration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleDuration
    {
      get { return _battleDuration; }
      set { _battleDuration = value; }
    }
    private long _battleStartTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"battleStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long battleStartTime
    {
      get { return _battleStartTime; }
      set { _battleStartTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}