//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BattleHistoryResp.proto
// Note: requires additional types generated from: BattleResultVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleHistoryResp")]
  public partial class BattleHistoryResp : global::ProtoBuf.IExtensible
  {
    public BattleHistoryResp() {}
    
    private readonly global::System.Collections.Generic.List<BattleResultVO> _attackBattleHistories = new global::System.Collections.Generic.List<BattleResultVO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"attackBattleHistories", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BattleResultVO> attackBattleHistories
    {
      get { return _attackBattleHistories; }
    }
  
    private readonly global::System.Collections.Generic.List<BattleResultVO> _defenseBattleHistories = new global::System.Collections.Generic.List<BattleResultVO>();
    [global::ProtoBuf.ProtoMember(2, Name=@"defenseBattleHistories", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BattleResultVO> defenseBattleHistories
    {
      get { return _defenseBattleHistories; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}