//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BattleResultVO.proto
// Note: requires additional types generated from: ResourceVO.proto
// Note: requires additional types generated from: BattleReplayVO.proto
// Note: requires additional types generated from: ArmyVO.proto
// Note: requires additional types generated from: SkillVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleResultVO")]
  public partial class BattleResultVO : global::ProtoBuf.IExtensible
  {
    public BattleResultVO() {}
    
    private int _percentage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"percentage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int percentage
    {
      get { return _percentage; }
      set { _percentage = value; }
    }
    private int _star;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private bool _useDonatedArmy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"useDonatedArmy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool useDonatedArmy
    {
      get { return _useDonatedArmy; }
      set { _useDonatedArmy = value; }
    }
    private readonly global::System.Collections.Generic.List<ArmyVO> _usedArmies = new global::System.Collections.Generic.List<ArmyVO>();
    [global::ProtoBuf.ProtoMember(4, Name=@"usedArmies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ArmyVO> usedArmies
    {
      get { return _usedArmies; }
    }
  
    private readonly global::System.Collections.Generic.List<SkillVO> _usedSkills = new global::System.Collections.Generic.List<SkillVO>();
    [global::ProtoBuf.ProtoMember(5, Name=@"usedSkills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillVO> usedSkills
    {
      get { return _usedSkills; }
    }
  
    private readonly global::System.Collections.Generic.List<ArmyVO> _killedDefenderDonatedArmies = new global::System.Collections.Generic.List<ArmyVO>();
    [global::ProtoBuf.ProtoMember(6, Name=@"killedDefenderDonatedArmies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ArmyVO> killedDefenderDonatedArmies
    {
      get { return _killedDefenderDonatedArmies; }
    }
  
    private readonly global::System.Collections.Generic.List<ResourceVO> _stolenResources = new global::System.Collections.Generic.List<ResourceVO>();
    [global::ProtoBuf.ProtoMember(7, Name=@"stolenResources", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResourceVO> stolenResources
    {
      get { return _stolenResources; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _brokenTraps = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(8, Name=@"brokenTraps", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> brokenTraps
    {
      get { return _brokenTraps; }
    }
  
    private int _rewardCrown = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rewardCrown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardCrown
    {
      get { return _rewardCrown; }
      set { _rewardCrown = value; }
    }
    private int _rewardGoldByCrownLevel = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"rewardGoldByCrownLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardGoldByCrownLevel
    {
      get { return _rewardGoldByCrownLevel; }
      set { _rewardGoldByCrownLevel = value; }
    }
    private int _rewardOilByCrownLevel = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"rewardOilByCrownLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardOilByCrownLevel
    {
      get { return _rewardOilByCrownLevel; }
      set { _rewardOilByCrownLevel = value; }
    }
    private long _timestamp;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private long _battleReplayId = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"battleReplayId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long battleReplayId
    {
      get { return _battleReplayId; }
      set { _battleReplayId = value; }
    }
    private long _peerId;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"peerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long peerId
    {
      get { return _peerId; }
      set { _peerId = value; }
    }
    private string _peerName = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"peerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string peerName
    {
      get { return _peerName; }
      set { _peerName = value; }
    }
    private string _peerClanName = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"peerClanName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string peerClanName
    {
      get { return _peerClanName; }
      set { _peerClanName = value; }
    }
    private long _peerClanId = default(long);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"peerClanId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long peerClanId
    {
      get { return _peerClanId; }
      set { _peerClanId = value; }
    }
    private int _peerCrown = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"peerCrown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int peerCrown
    {
      get { return _peerCrown; }
      set { _peerCrown = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}