//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BattleReplayResp.proto
// Note: requires additional types generated from: BattleReplayVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleReplayResp")]
  public partial class BattleReplayResp : global::ProtoBuf.IExtensible
  {
    public BattleReplayResp() {}
    
    private BattleReplayVO _battleReplayVO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"battleReplayVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BattleReplayVO battleReplayVO
    {
      get { return _battleReplayVO; }
      set { _battleReplayVO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}