//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BattleResultReq.proto
// Note: requires additional types generated from: BattleResultVO.proto
// Note: requires additional types generated from: BattleReplayVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleResultReq")]
  public partial class BattleResultReq : global::ProtoBuf.IExtensible
  {
    public BattleResultReq() {}
    
    private BattleResultVO _battleResultVO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"battleResultVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BattleResultVO battleResultVO
    {
      get { return _battleResultVO; }
      set { _battleResultVO = value; }
    }
    private BattleReplayVO _battleReplayVO = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"battleReplayVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BattleReplayVO battleReplayVO
    {
      get { return _battleReplayVO; }
      set { _battleReplayVO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}