//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuildingCompleteReq.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingCompleteReq")]
  public partial class BuildingCompleteReq : global::ProtoBuf.IExtensible
  {
    public BuildingCompleteReq() {}
    
    private BuildingCompleteReq.CompleteType _completeType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"completeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BuildingCompleteReq.CompleteType completeType
    {
      get { return _completeType; }
      set { _completeType = value; }
    }
    private long _sid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"CompleteType")]
    public enum CompleteType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=1)]
      Normal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CompleteImmediately", Value=2)]
      CompleteImmediately = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}