//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuildingConsReq.proto
// Note: requires additional types generated from: BuildingVO.proto
// Note: requires additional types generated from: ResourceType.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingConsReq")]
  public partial class BuildingConsReq : global::ProtoBuf.IExtensible
  {
    public BuildingConsReq() {}
    
    private BuildingVO _buildingVO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buildingVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BuildingVO buildingVO
    {
      get { return _buildingVO; }
      set { _buildingVO = value; }
    }
    private ResourceType _resourceType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ResourceType resourceType
    {
      get { return _resourceType; }
      set { _resourceType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}