//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuildingUpgradeReq.proto
// Note: requires additional types generated from: ResourceType.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingUpgradeReq")]
  public partial class BuildingUpgradeReq : global::ProtoBuf.IExtensible
  {
    public BuildingUpgradeReq() {}
    
    private long _sid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private ResourceType _resourceType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ResourceType resourceType
    {
      get { return _resourceType; }
      set { _resourceType = value; }
    }
    private bool _cancel = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cancel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool cancel
    {
      get { return _cancel; }
      set { _cancel = value; }
    }
    private long _endTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}