//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuildingVO.proto
// Note: requires additional types generated from: ProductionBuildingVO.proto
// Note: requires additional types generated from: ResourceBuildingVO.proto
// Note: requires additional types generated from: ResearchBuildingVO.proto
// Note: requires additional types generated from: TrapBuildingVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingVO")]
  public partial class BuildingVO : global::ProtoBuf.IExtensible
  {
    public BuildingVO() {}
    
    private long _sid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private int _cid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cid
    {
      get { return _cid; }
      set { _cid = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private BuildingVO.BuildingStatus _buildingStatus = BuildingVO.BuildingStatus.On;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"buildingStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(BuildingVO.BuildingStatus.On)]
    public BuildingVO.BuildingStatus buildingStatus
    {
      get { return _buildingStatus; }
      set { _buildingStatus = value; }
    }
    private long _endTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private ResourceBuildingVO _resourceBuildingVO = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"resourceBuildingVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ResourceBuildingVO resourceBuildingVO
    {
      get { return _resourceBuildingVO; }
      set { _resourceBuildingVO = value; }
    }
    private ProductionBuildingVO _productionBuildingVO = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"productionBuildingVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProductionBuildingVO productionBuildingVO
    {
      get { return _productionBuildingVO; }
      set { _productionBuildingVO = value; }
    }
    private ResearchBuildingVO _researchBuildingVO = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"researchBuildingVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ResearchBuildingVO researchBuildingVO
    {
      get { return _researchBuildingVO; }
      set { _researchBuildingVO = value; }
    }
    private TrapBuildingVO _trapBuildingVO = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"trapBuildingVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TrapBuildingVO trapBuildingVO
    {
      get { return _trapBuildingVO; }
      set { _trapBuildingVO = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"BuildingStatus")]
    public enum BuildingStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"On", Value=1)]
      On = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Construct", Value=2)]
      Construct = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Upgrade", Value=3)]
      Upgrade = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}