//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuyResourceReq.proto
// Note: requires additional types generated from: ResourceVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyResourceReq")]
  public partial class BuyResourceReq : global::ProtoBuf.IExtensible
  {
    public BuyResourceReq() {}
    
    private ResourceVO _resourceVO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resourceVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ResourceVO resourceVO
    {
      get { return _resourceVO; }
      set { _resourceVO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}