//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CampVO.proto
// Note: requires additional types generated from: BuildingVO.proto
// Note: requires additional types generated from: ArmyVO.proto
// Note: requires additional types generated from: PlayerVO.proto
// Note: requires additional types generated from: SkillVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CampVO")]
  public partial class CampVO : global::ProtoBuf.IExtensible
  {
    public CampVO() {}
    
    private PlayerVO _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerVO player
    {
      get { return _player; }
      set { _player = value; }
    }
    private readonly global::System.Collections.Generic.List<BuildingVO> _buildings = new global::System.Collections.Generic.List<BuildingVO>();
    [global::ProtoBuf.ProtoMember(2, Name=@"buildings", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BuildingVO> buildings
    {
      get { return _buildings; }
    }
  
    private readonly global::System.Collections.Generic.List<ArmyVO> _armies = new global::System.Collections.Generic.List<ArmyVO>();
    [global::ProtoBuf.ProtoMember(3, Name=@"armies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ArmyVO> armies
    {
      get { return _armies; }
    }
  
    private readonly global::System.Collections.Generic.List<ArmyVO> _donatedArmies = new global::System.Collections.Generic.List<ArmyVO>();
    [global::ProtoBuf.ProtoMember(4, Name=@"donatedArmies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ArmyVO> donatedArmies
    {
      get { return _donatedArmies; }
    }
  
    private readonly global::System.Collections.Generic.List<SkillVO> _skills = new global::System.Collections.Generic.List<SkillVO>();
    [global::ProtoBuf.ProtoMember(5, Name=@"skills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillVO> skills
    {
      get { return _skills; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}