//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChargeDiamondReq.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChargeDiamondReq")]
  public partial class ChargeDiamondReq : global::ProtoBuf.IExtensible
  {
    public ChargeDiamondReq() {}
    
    private int _diamondCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"diamondCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamondCount
    {
      get { return _diamondCount; }
      set { _diamondCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}