//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CompleteInfoReq.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompleteInfoReq")]
  public partial class CompleteInfoReq : global::ProtoBuf.IExtensible
  {
    public CompleteInfoReq() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _passwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passwd
    {
      get { return _passwd; }
      set { _passwd = value; }
    }
    private string _phoneNum = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"phoneNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phoneNum
    {
      get { return _phoneNum; }
      set { _phoneNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}