//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FightSearchReq.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightSearchReq")]
  public partial class FightSearchReq : global::ProtoBuf.IExtensible
  {
    public FightSearchReq() {}
    
    private FightSearchReq.SearchType _searchType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"searchType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FightSearchReq.SearchType searchType
    {
      get { return _searchType; }
      set { _searchType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SearchType")]
    public enum SearchType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVE", Value=1)]
      PVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_NORMAL", Value=2)]
      PVP_NORMAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_HIGH", Value=3)]
      PVP_HIGH = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}