//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoginResp.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResp")]
  public partial class LoginResp : global::ProtoBuf.IExtensible
  {
    public LoginResp() {}
    
    private string _authToken;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"authToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string authToken
    {
      get { return _authToken; }
      set { _authToken = value; }
    }
    private long _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _nextItemSid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nextItemSid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nextItemSid
    {
      get { return _nextItemSid; }
      set { _nextItemSid = value; }
    }
    private long _currentTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"currentTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long currentTime
    {
      get { return _currentTime; }
      set { _currentTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}