//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MoveBuildingReq.proto
// Note: requires additional types generated from: BuildingVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveBuildingReq")]
  public partial class MoveBuildingReq : global::ProtoBuf.IExtensible
  {
    public MoveBuildingReq() {}
    
    private readonly global::System.Collections.Generic.List<BuildingVO> _building = new global::System.Collections.Generic.List<BuildingVO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"building", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BuildingVO> building
    {
      get { return _building; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}