//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NoAuthLoginReq.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NoAuthLoginReq")]
  public partial class NoAuthLoginReq : global::ProtoBuf.IExtensible
  {
    public NoAuthLoginReq() {}
    
    private string _machineId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"machineId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string machineId
    {
      get { return _machineId; }
      set { _machineId = value; }
    }
    private int _raceType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"raceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int raceType
    {
      get { return _raceType; }
      set { _raceType = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}