//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlayerLoginSimpleVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerLoginSimpleVO")]
  public partial class PlayerLoginSimpleVO : global::ProtoBuf.IExtensible
  {
    public PlayerLoginSimpleVO() {}
    
    private long _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _raceType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"raceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int raceType
    {
      get { return _raceType; }
      set { _raceType = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private int _userLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"userLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userLevel
    {
      get { return _userLevel; }
      set { _userLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}