//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlayerVO.proto
// Note: requires additional types generated from: ResourceVO.proto
// Note: requires additional types generated from: ArmyExpVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerVO")]
  public partial class PlayerVO : global::ProtoBuf.IExtensible
  {
    public PlayerVO() {}
    
    private long _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _raceType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"raceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int raceType
    {
      get { return _raceType; }
      set { _raceType = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _experience = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int experience
    {
      get { return _experience; }
      set { _experience = value; }
    }
    private int _crown = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"crown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int crown
    {
      get { return _crown; }
      set { _crown = value; }
    }
    private readonly global::System.Collections.Generic.List<ResourceVO> _resources = new global::System.Collections.Generic.List<ResourceVO>();
    [global::ProtoBuf.ProtoMember(7, Name=@"resources", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ResourceVO> resources
    {
      get { return _resources; }
    }
  
    private readonly global::System.Collections.Generic.List<ArmyExpVO> _armyShop = new global::System.Collections.Generic.List<ArmyExpVO>();
    [global::ProtoBuf.ProtoMember(8, Name=@"armyShop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ArmyExpVO> armyShop
    {
      get { return _armyShop; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _skillShop = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"skillShop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skillShop
    {
      get { return _skillShop; }
    }
  
    private int _baseId = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"baseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int baseId
    {
      get { return _baseId; }
      set { _baseId = value; }
    }
    private int _maxWorker = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"maxWorker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxWorker
    {
      get { return _maxWorker; }
      set { _maxWorker = value; }
    }
    private int _freeWorker = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"freeWorker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int freeWorker
    {
      get { return _freeWorker; }
      set { _freeWorker = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}