//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProductionBuildingVO.proto
// Note: requires additional types generated from: ProductionItemVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProductionBuildingVO")]
  public partial class ProductionBuildingVO : global::ProtoBuf.IExtensible
  {
    public ProductionBuildingVO() {}
    
    private readonly global::System.Collections.Generic.List<ProductionItemVO> _productionItems = new global::System.Collections.Generic.List<ProductionItemVO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"productionItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProductionItemVO> productionItems
    {
      get { return _productionItems; }
    }
  
    private long _endTime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}