//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProductionReq.proto
// Note: requires additional types generated from: ProductionItemVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProductionReq")]
  public partial class ProductionReq : global::ProtoBuf.IExtensible
  {
    public ProductionReq() {}
    
    private ProductionReq.ProductionRequestType _productionRequestType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"productionRequestType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProductionReq.ProductionRequestType productionRequestType
    {
      get { return _productionRequestType; }
      set { _productionRequestType = value; }
    }
    private long _sid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private ProductionItemVO _productionItemVO = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"productionItemVO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProductionItemVO productionItemVO
    {
      get { return _productionItemVO; }
      set { _productionItemVO = value; }
    }
    private long _time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _diamondCount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"diamondCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamondCount
    {
      get { return _diamondCount; }
      set { _diamondCount = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ProductionRequestType")]
    public enum ProductionRequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Add", Value=1)]
      Add = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Remove", Value=2)]
      Remove = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Complete", Value=3)]
      Complete = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CompleteImmediately", Value=4)]
      CompleteImmediately = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}