//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ReqWrapper.proto
// Note: requires additional types generated from: ArmyUpgradeReq.proto
// Note: requires additional types generated from: AuthLoginReq.proto
// Note: requires additional types generated from: BuildingConsReq.proto
// Note: requires additional types generated from: BuildingUpgradeReq.proto
// Note: requires additional types generated from: CampReq.proto
// Note: requires additional types generated from: GatherReq.proto
// Note: requires additional types generated from: NoAuthLoginReq.proto
// Note: requires additional types generated from: ProductionReq.proto
// Note: requires additional types generated from: BuildingCompleteReq.proto
// Note: requires additional types generated from: BattleResultReq.proto
// Note: requires additional types generated from: BattleHistoryReq.proto
// Note: requires additional types generated from: BattleReplayReq.proto
// Note: requires additional types generated from: PlayerListReq.proto
// Note: requires additional types generated from: ChangeAccountReq.proto
// Note: requires additional types generated from: CompleteInfoReq.proto
// Note: requires additional types generated from: FightSearchReq.proto
// Note: requires additional types generated from: MoveBuildingReq.proto
// Note: requires additional types generated from: TrapRefillReq.proto
// Note: requires additional types generated from: ResearchReq.proto
// Note: requires additional types generated from: BuyResourceReq.proto
// Note: requires additional types generated from: ChargeDiamondReq.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqWrapper")]
  public partial class ReqWrapper : global::ProtoBuf.IExtensible
  {
    public ReqWrapper() {}
    
    private ReqWrapper.RequestType _requestType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"requestType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ReqWrapper.RequestType requestType
    {
      get { return _requestType; }
      set { _requestType = value; }
    }
    private ArmyUpgradeReq _armyUpgradeReq = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"armyUpgradeReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ArmyUpgradeReq armyUpgradeReq
    {
      get { return _armyUpgradeReq; }
      set { _armyUpgradeReq = value; }
    }
    private AuthLoginReq _authLoginReq = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"authLoginReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AuthLoginReq authLoginReq
    {
      get { return _authLoginReq; }
      set { _authLoginReq = value; }
    }
    private BuildingConsReq _buildingConsReq = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buildingConsReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BuildingConsReq buildingConsReq
    {
      get { return _buildingConsReq; }
      set { _buildingConsReq = value; }
    }
    private BuildingUpgradeReq _buildingUpReq = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"buildingUpReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BuildingUpgradeReq buildingUpReq
    {
      get { return _buildingUpReq; }
      set { _buildingUpReq = value; }
    }
    private CampReq _campReq = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"campReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CampReq campReq
    {
      get { return _campReq; }
      set { _campReq = value; }
    }
    private GatherReq _gatherReq = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gatherReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GatherReq gatherReq
    {
      get { return _gatherReq; }
      set { _gatherReq = value; }
    }
    private NoAuthLoginReq _noAuthLoginReq = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"noAuthLoginReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public NoAuthLoginReq noAuthLoginReq
    {
      get { return _noAuthLoginReq; }
      set { _noAuthLoginReq = value; }
    }
    private ProductionReq _productionReq = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"productionReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProductionReq productionReq
    {
      get { return _productionReq; }
      set { _productionReq = value; }
    }
    private BuildingCompleteReq _buildingCompleteReq = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"buildingCompleteReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BuildingCompleteReq buildingCompleteReq
    {
      get { return _buildingCompleteReq; }
      set { _buildingCompleteReq = value; }
    }
    private BattleResultReq _battleResultReq = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"battleResultReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BattleResultReq battleResultReq
    {
      get { return _battleResultReq; }
      set { _battleResultReq = value; }
    }
    private BattleHistoryReq _battleHistoryReq = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"battleHistoryReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BattleHistoryReq battleHistoryReq
    {
      get { return _battleHistoryReq; }
      set { _battleHistoryReq = value; }
    }
    private BattleReplayReq _battleReplayReq = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"battleReplayReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BattleReplayReq battleReplayReq
    {
      get { return _battleReplayReq; }
      set { _battleReplayReq = value; }
    }
    private PlayerListReq _playerListReq = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"playerListReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PlayerListReq playerListReq
    {
      get { return _playerListReq; }
      set { _playerListReq = value; }
    }
    private ChangeAccountReq _changeAccountReq = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"changeAccountReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ChangeAccountReq changeAccountReq
    {
      get { return _changeAccountReq; }
      set { _changeAccountReq = value; }
    }
    private CompleteInfoReq _completeInfoReq = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"completeInfoReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CompleteInfoReq completeInfoReq
    {
      get { return _completeInfoReq; }
      set { _completeInfoReq = value; }
    }
    private FightSearchReq _fightSearchReq = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"fightSearchReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FightSearchReq fightSearchReq
    {
      get { return _fightSearchReq; }
      set { _fightSearchReq = value; }
    }
    private MoveBuildingReq _moveBuildingReq = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"moveBuildingReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MoveBuildingReq moveBuildingReq
    {
      get { return _moveBuildingReq; }
      set { _moveBuildingReq = value; }
    }
    private TrapRefillReq _trapRefillReq = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"trapRefillReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TrapRefillReq trapRefillReq
    {
      get { return _trapRefillReq; }
      set { _trapRefillReq = value; }
    }
    private ResearchReq _researchReq = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"researchReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ResearchReq researchReq
    {
      get { return _researchReq; }
      set { _researchReq = value; }
    }
    private BuyResourceReq _buyResourceReq = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"buyResourceReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BuyResourceReq buyResourceReq
    {
      get { return _buyResourceReq; }
      set { _buyResourceReq = value; }
    }
    private ChargeDiamondReq _chargeDiamondReq = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"chargeDiamondReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ChargeDiamondReq chargeDiamondReq
    {
      get { return _chargeDiamondReq; }
      set { _chargeDiamondReq = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RequestType")]
    public enum RequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArmyUpgrade", Value=2)]
      ArmyUpgrade = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AuthLogin", Value=3)]
      AuthLogin = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuildingCons", Value=4)]
      BuildingCons = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuildingUpgrade", Value=5)]
      BuildingUpgrade = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Camp", Value=6)]
      Camp = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gather", Value=7)]
      Gather = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoAuthLogin", Value=8)]
      NoAuthLogin = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Production", Value=9)]
      Production = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuildingComplete", Value=10)]
      BuildingComplete = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BattleResult", Value=11)]
      BattleResult = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BattleHistory", Value=12)]
      BattleHistory = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BattleReplay", Value=13)]
      BattleReplay = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerList", Value=14)]
      PlayerList = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeAccount", Value=15)]
      ChangeAccount = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CompleteInfo", Value=16)]
      CompleteInfo = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FightSearch", Value=17)]
      FightSearch = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveBuilding", Value=18)]
      MoveBuilding = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TrapRefill", Value=19)]
      TrapRefill = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Research", Value=20)]
      Research = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BuyResource", Value=21)]
      BuyResource = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChargeDiamond", Value=22)]
      ChargeDiamond = 22
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}