//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResearchReq.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResearchReq")]
  public partial class ResearchReq : global::ProtoBuf.IExtensible
  {
    public ResearchReq() {}
    
    private ResearchReq.ResearchRequestType _researchRequestType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"researchRequestType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ResearchReq.ResearchRequestType researchRequestType
    {
      get { return _researchRequestType; }
      set { _researchRequestType = value; }
    }
    private int _cid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cid
    {
      get { return _cid; }
      set { _cid = value; }
    }
    private long _currentTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"currentTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long currentTime
    {
      get { return _currentTime; }
      set { _currentTime = value; }
    }
    private int _diamondCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"diamondCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamondCount
    {
      get { return _diamondCount; }
      set { _diamondCount = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResearchRequestType")]
    public enum ResearchRequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Research", Value=1)]
      Research = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Complete", Value=2)]
      Complete = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CompleteImmediately", Value=3)]
      CompleteImmediately = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}