//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResourceType.proto
namespace com.pureland.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"ResourceType")]
    public enum ResourceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gold", Value=1)]
      Gold = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Oil", Value=2)]
      Oil = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Diamond", Value=3)]
      Diamond = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Medal", Value=4)]
      Medal = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Number", Value=5)]
      Number = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RMB", Value=6)]
      RMB = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GoldOrOil", Value=7)]
      GoldOrOil = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewOil", Value=8)]
      NewOil = 8
    }
  
}