//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResourceBuildingVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceBuildingVO")]
  public partial class ResourceBuildingVO : global::ProtoBuf.IExtensible
  {
    public ResourceBuildingVO() {}
    
    private long _lastGatherTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lastGatherTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lastGatherTime
    {
      get { return _lastGatherTime; }
      set { _lastGatherTime = value; }
    }
    private int _storage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"storage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int storage
    {
      get { return _storage; }
      set { _storage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}