//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RespWrapper.proto
// Note: requires additional types generated from: LoginResp.proto
// Note: requires additional types generated from: PlayerListResp.proto
// Note: requires additional types generated from: CampResp.proto
// Note: requires additional types generated from: BattleHistoryResp.proto
// Note: requires additional types generated from: BattleReplayResp.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespWrapper")]
  public partial class RespWrapper : global::ProtoBuf.IExtensible
  {
    public RespWrapper() {}
    
    private LoginResp _loginResp = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"loginResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public LoginResp loginResp
    {
      get { return _loginResp; }
      set { _loginResp = value; }
    }
    private PlayerListResp _playerListResp = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerListResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PlayerListResp playerListResp
    {
      get { return _playerListResp; }
      set { _playerListResp = value; }
    }
    private CampResp _campResp = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"campResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CampResp campResp
    {
      get { return _campResp; }
      set { _campResp = value; }
    }
    private BattleHistoryResp _battleHistoryResp = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"battleHistoryResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BattleHistoryResp battleHistoryResp
    {
      get { return _battleHistoryResp; }
      set { _battleHistoryResp = value; }
    }
    private BattleReplayResp _battleReplayResp = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"battleReplayResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BattleReplayResp battleReplayResp
    {
      get { return _battleReplayResp; }
      set { _battleReplayResp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}