//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TrapBuildingVO.proto
namespace com.pureland.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrapBuildingVO")]
  public partial class TrapBuildingVO : global::ProtoBuf.IExtensible
  {
    public TrapBuildingVO() {}
    
    private bool _broken;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"broken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool broken
    {
      get { return _broken; }
      set { _broken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}